"""update users table for nima

Revision ID: 335789bfc30f
Revises: 53e9928620e1
Create Date: 2026-10-04 09:26:06.737168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '335789bfc30f'
down_revision: Union[str, Sequence[str], None] = '53e9928620e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'users',
        sa.Column('name', sa.String(), nullable=False, server_default='')
    )
    op.add_column(
        'users',
        sa.Column('phone', sa.String(), nullable=False, server_default='')
    )
    op.add_column(
        'users',
        sa.Column('role', sa.String(), nullable=False, server_default='client')
    )

    op.alter_column(
        'users',
        'username',
        existing_type=sa.VARCHAR(),
        nullable=False
    )
    op.alter_column(
        'users',
        'email',
        existing_type=sa.VARCHAR(),
        nullable=False
    )
    op.alter_column(
        'users',
        'password',
        existing_type=sa.VARCHAR(),
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'role')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
