"""replace donation location with coordinates

Revision ID: 580daf98a544
Revises: 97cd4aa301d3
Create Date: 2026-10-05 13:50:11.972374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '580daf98a544'
down_revision: Union[str, Sequence[str], None] = '97cd4aa301d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('donations', sa.Column('longitude', sa.Float(), nullable=True))
    op.drop_column('donations', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('donations', 'longitude')
    op.drop_column('donations', 'latitude')
    # ### end Alembic commands ###
