"""create donations and items tables

Revision ID: eec429ce5c6e
Revises: 335789bfc30f
Create Date: 2026-10-04 10:08:40.788444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eec429ce5c6e'
down_revision: Union[str, Sequence[str], None] = '335789bfc30f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('collector_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('pickup_house', sa.String(), nullable=False),
    sa.Column('pickup_road', sa.String(), nullable=False),
    sa.Column('pickup_block', sa.String(), nullable=False),
    sa.Column('pickup_area', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('preferred_pickup_date', sa.Date(), nullable=False),
    sa.Column('preferred_pickup_time', sa.Time(), nullable=False),
    sa.Column('proof_photo_url', sa.String(), nullable=True),
    sa.Column('admin_approved', sa.Boolean(), nullable=False),
    sa.Column('pickup_successful', sa.Boolean(), nullable=False),
    sa.Column('failed_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_id'), 'donations', ['id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_donations_id'), table_name='donations')
    op.drop_table('donations')
    # ### end Alembic commands ###
